### ISSUE TITLE
save scale and offset (SPIFFS)

### ISSUE THREAD

**Issue by Albalate** [RobTillaart/HX711#18]
maybe you would like an example of saving the data to a file on esp32 or esp8366 using SPIFFS?.
I'm building it and I thought we could add it
regards

**Comment by RobTillaart** [comment]
Good examples are always welcome.

**Comment by RobTillaart** [comment]
The name should be something like
HX711_spiffs_esp32.ino

**Comment by RobTillaart** [comment]
@Albalate 
As there is no progress for a month I close this issue.
Feel free to reopen if example is available
