### ISSUE TITLE
Display Peak Value 

### ISSUE THREAD

**Issue by jclark0193** [RobTillaart/HX711#36]
I have a meter that needs to display only the peak value sensed by the load cell.

**Comment by RobTillaart** [comment]
Thanks for the question.
Just add a global variable to your project.
Initialize it with the first read of the load cell.
Compare every next measurement with this var and keep the largest.
Display the var when needed.

(Note this is not a function that will be build into the library)

**Comment by jclark0193** [comment]
Thanks Rob. I just purchased my first Arduino, with zero experience programming. Trying to build my first project. Thanks for the help.

**Comment by RobTillaart** [comment]
Start small, look at other peoples sketches and try to understand how they work.

**Comment by RobTillaart** [comment]
As issue has no concrete question anymore it is closed.
