### ISSUE TITLE
Request for Power Saving Feature

### ISSUE THREAD

**Issue by cbijon** [RobTillaart/HX711#45]
As a user of the HX711 library, I have noticed that there is no built-in power saving feature to reduce power consumption during idle periods.

Request:
I would like to propose the addition of a power saving feature in the HX711 library. This feature could include methods like .powerUp() and .powerDown() to manage the power state of the HX711 module. This would be particularly useful for scenarios where power consumption needs to be minimized during periods of inactivity.

**Comment by RobTillaart** [comment]
Thanks for the request, will take several days before I have time to dive into it as I have a lot of work in progress.

**Comment by RobTillaart** [comment]
Some first thoughts… four functions needed:
- **void setPowerPin(uint8_t pin)** make it possible.
- **bool powerUp()** idem
- **bool powerDown()** idem
- **bool isPowerOn()** check state.


Possibly one need a timestamp when powered up.
If no power pin is defined the up/down functions will return false.
Default state must be "POWERUP", to be backwards compatible and to be usable for people who do not use this feature.

Possibly a derived class implements these extra functions.
If the user wants to use the feature it is his responsibility to check state before reading a load.

The feature does not implement battery monitoring or voltage level or current current. Outside scope of a loadcell.
