### ISSUE TITLE
Fast processor read() delay

### ISSUE THREAD

**Issue by palmerr23** [RobTillaart/HX711#46]
Thanks for the library, it works well!

To answer the question embedded in the code at line 135 in the cpp file, you do not need the delayMicroseconds(1) for a Pico running at 240MHz (PD_SCK is 500nS) in _shiftIn( ) **or** read( ).  

The delay( ) treatment should probably be the same in both places.

It would be useful, however to have an option, as a Teensy 4 and other processors running at > 500MHz are likely to need them in **both** read( ) **and** _shiftIn( ).
```cpp
  while (m > 0)
  {
    //  delayMicroSeconds(1) needed for fast processors?
    digitalWrite(_clockPin, HIGH);
    if(_fast_processor)
	delayMicroseconds(1);
    digitalWrite(_clockPin, LOW);
    if(_fast_processor)
	delayMicroseconds(1);
    m--;
  }
```
BTW, I tested the B input and it seems fine.

A pull request will be forthcoming.

I hope this is useful.

**Comment by RobTillaart** [comment]
Thanks for this feedback,
Definitely useful to hear.

**Comment by RobTillaart** [comment]
- Merged the PR,
- Will increase version asap
- will add the change also to HX711_MP repo (asap)

**Comment by RobTillaart** [comment]
@palmerr23 
HX711 & HX711_MP released
Again thanks for your addition / feedback
